# This is a basic workflow to help you get started with Actions

name: MyIP
env:
  Application-Name : "Introduction to Github Actions"
  Version          : "Version of last Commit is ${{github.sha}}"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testing:
   runs-on: ubuntu-latest

   steps:
   - name: Clone Repository
     uses: action/checkout@v1
 
   - name: Print Hello Message
     run: echo "Hello World from Testing"

   - name: Execute few commands
     run: |
       echo "Hello 1"      
       echo "Hello 2"
       echo "Application name is ${{env.Application-Name}}"


   - name: List Current Folder
     run: ls -la

  depoyment:
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
    - name: Print Hello World
      run: echo "Hello world from Deployment"
    - name: Printing Hash of Commit
      run: echo "Sha sum of commit is ${{env.Version}}"
    
    - name: Test AWS-cli
      run: aws --version
    - name: Test Zip
      run: zip
